In [16]:
# import numpy
# create array x

import numpy as np

x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [17]:
# print the shape of x

np.shape(x)

(12,)

In [21]:
# create a two dimensional array

x = np.reshape(x, (3,4))

print x

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
# print shape of 2d array

np.shape(x)

(3, 4)

In [23]:
# reshape the array to 2 x 6

x = np.reshape(x, (2,6))
print x

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [44]:
# reshape the array to 1 x 12

x = np.reshape (x, (2,6))

print x

[[ 1  5  9  2  6 10]
 [ 3  7 11  4  8 12]]


In [45]:
# transpose the array

#x = np.transpose(x)

# or

x.T

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [ 2,  4],
       [ 6,  8],
       [10, 12]])

In [36]:
# indexing method 1

x[0]

array([1, 5, 9])

In [35]:
# indexing method 2

x[1][2]

10

In [55]:
# indexing method 3

x[1,5]

12

In [12]:
# indexing method 4



In [11]:
# indexing method 5

In [10]:
# indexing method 6