In [33]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

In [2]:
a


array([1, 2, 3, 4, 5])

In [4]:
reshaped_a = a.reshape(1,-1)

In [5]:
reshaped_a

array([[1, 2, 3, 4, 5]])

In [6]:
reshaped_a.shape

(1, 5)

In [7]:
reshaped_a.ndim

2

In [8]:
reshaped_a.T

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [19]:
ar1 = np.array([1,2,3,4,5])

print ar1
print type(ar1)
print ar1.shape
print ar1.ndim

[1 2 3 4 5]
<type 'numpy.ndarray'>
(5,)
1


In [18]:
mat_ar1 = ar1.reshape(1,-1)

print mat_ar1
print type(mat_ar1)
print mat_ar1.shape
print mat_ar1.ndim

[[1 2 3 4 5]]
<type 'numpy.ndarray'>
(1, 5)
2


In [24]:
zf = np.array([1,2,3,4,5.0])
zs = np.array([1,2,3,4,'five'])

In [25]:
print zf.dtype
print zs.dtype

float64
|S21


In [29]:
print a
print b

[1 2 3 4 5]
[5 4 3 2 1]


In [26]:
b

array([5, 4, 3, 2, 1])

In [16]:
np.add(a, b)

array([6, 6, 6, 6, 6])

In [17]:
np.subtract(a, b)

array([-4, -2,  0,  2,  4])

In [14]:
np.dot(a, b)

35

In [34]:
np.dot(b, a)

35

In [61]:
%%timeit
list_one = [1,3,5,7,9]
list_two = [2,4,6,8,10]

def dotProduct(item1, item2):
    
    x = 0
    
    for i in range(len(item1)):
        mini_prod = item1[i] * item2[i]
        x += mini_prod
    return x

dotProduct(list_one, list_two)

The slowest run took 7.02 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.56 µs per loop


In [60]:
np.dot(list_one, list_two)

The slowest run took 1912.16 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.72 µs per loop


In [45]:
zip(list_one, list_two)

[(1, 2), (3, 4), (5, 6), (7, 8), (9, 10)]

In [62]:
%%timeit
def inLine_dotProd(a1, a2):

    dot_product = sum([x*y for x,y in zip(a1,a2)])
    return dot_product
    
inLine_dotProd(list_one, list_two)

The slowest run took 5.46 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 1.83 µs per loop
